// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEAkmLB8PUQAN3ro2J8nCvaDhmBYtvSL8',
    appId: '1:733773769021:web:98f5b34483dcb5f73b7d54',
    messagingSenderId: '733773769021',
    projectId: 'fresher-arena',
    authDomain: 'fresher-arena.firebaseapp.com',
    storageBucket: 'fresher-arena.firebasestorage.app',
    measurementId: 'G-4GPXLDMEZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUqvTz-lh6ZYr2bsxbSSwdZSAsMdzpvME',
    appId: '1:733773769021:android:6ecf645086aae8bb3b7d54',
    messagingSenderId: '733773769021',
    projectId: 'fresher-arena',
    storageBucket: 'fresher-arena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATRjSapjDJpnoeg_sr95v1hUXkNTy4NSk',
    appId: '1:733773769021:ios:d5438855247a43bd3b7d54',
    messagingSenderId: '733773769021',
    projectId: 'fresher-arena',
    storageBucket: 'fresher-arena.firebasestorage.app',
    iosBundleId: 'com.example.fresherArenaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATRjSapjDJpnoeg_sr95v1hUXkNTy4NSk',
    appId: '1:733773769021:ios:d5438855247a43bd3b7d54',
    messagingSenderId: '733773769021',
    projectId: 'fresher-arena',
    storageBucket: 'fresher-arena.firebasestorage.app',
    iosBundleId: 'com.example.fresherArenaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEAkmLB8PUQAN3ro2J8nCvaDhmBYtvSL8',
    appId: '1:733773769021:web:910524c78d60e3fb3b7d54',
    messagingSenderId: '733773769021',
    projectId: 'fresher-arena',
    authDomain: 'fresher-arena.firebaseapp.com',
    storageBucket: 'fresher-arena.firebasestorage.app',
    measurementId: 'G-96MQ6PF4XS',
  );
}
